import { Conversation, Message } from "@/types/inbox";

export const mockConversations: Conversation[] = [
  {
    id: "1",
    name: "Maria Silva",
    avatar: "MS",
    lastMessage: "Olá, meu cartão de crédito não está funcionando.",
    timestamp: "5min",
    unread: true,
    unreadCount: 3,
    channel: "whatsapp",
    tags: ["Urgente", "Pagamento"],
    isPinned: true,
    isImportant: true,
    phone: "+55 11 98765-4321",
    callHistory: [
      {
        id: "call1",
        type: "incoming",
        date: "10 Nov, 14:30",
        duration: 245,
      },
      {
        id: "call2",
        type: "outgoing",
        date: "9 Nov, 10:15",
        duration: 180,
      },
      {
        id: "call3",
        type: "missed",
        date: "8 Nov, 16:45",
      },
    ],
    appointments: [
      {
        id: "appt1",
        title: "Consulta sobre pagamento",
        date: "15 Nov, 2024",
        time: "14:00",
        status: "scheduled",
      },
      {
        id: "appt2",
        title: "Follow-up cartão",
        date: "12 Nov, 2024",
        time: "10:30",
        status: "completed",
      },
    ],
    assignedTo: {
      id: "user1",
      name: "June Jensen",
      avatar: "JJ",
    },
    status: "open",
  },
  {
    id: "2",
    name: "João Santos",
    avatar: "JS",
    lastMessage: "Tenho uma dúvida sobre meu pedido",
    timestamp: "15min",
    unread: true,
    unreadCount: 1,
    channel: "facebook",
    tags: ["Pedido"],
    isPinned: false,
    isImportant: false,
    phone: "+55 21 99876-5432",
    callHistory: [
      {
        id: "call1",
        type: "outgoing",
        date: "10 Nov, 09:20",
        duration: 320,
      },
    ],
    appointments: [
      {
        id: "appt1",
        title: "Entrega do pedido #1234",
        date: "18 Nov, 2024",
        time: "15:00",
        status: "scheduled",
      },
    ],
    assignedTo: {
      id: "user1",
      name: "June Jensen",
      avatar: "JJ",
    },
    status: "open",
  },
  {
    id: "3",
    name: "Ana Costa",
    avatar: "AC",
    lastMessage: "O aplicativo está fora do ar?",
    timestamp: "1h",
    unread: true,
    unreadCount: 2,
    channel: "whatsapp",
    tags: ["Suporte"],
    isPinned: false,
    isImportant: false,
    phone: "+55 11 91234-5678",
    callHistory: [
      {
        id: "call1",
        type: "incoming",
        date: "10 Nov, 11:00",
        duration: 450,
      },
      {
        id: "call2",
        type: "missed",
        date: "9 Nov, 14:20",
      },
      {
        id: "call3",
        type: "outgoing",
        date: "9 Nov, 14:25",
        duration: 380,
      },
    ],
    assignedTo: {
      id: "user1",
      name: "June Jensen",
      avatar: "JJ",
    },
    status: "open",
  },
  {
    id: "4",
    name: "Pedro Oliveira",
    avatar: "PO",
    lastMessage: "Pode me enviar a documentação?",
    timestamp: "2h",
    unread: false,
    unreadCount: 0,
    channel: "instagram",
    tags: [],
    isPinned: false,
    isImportant: false,
    phone: "+55 31 98765-4321",
    assignedTo: {
      id: "user1",
      name: "June Jensen",
      avatar: "JJ",
    },
    status: "open",
  },
  {
    id: "5",
    name: "Carla Mendes",
    avatar: "CM",
    lastMessage: "Criei uma nova página mas não está aparecendo",
    timestamp: "3h",
    unread: false,
    unreadCount: 0,
    channel: "whatsapp",
    tags: ["Bug"],
    isPinned: false,
    isImportant: true,
    phone: "+55 41 97654-3210",
    callHistory: [
      {
        id: "call1",
        type: "outgoing",
        date: "10 Nov, 12:00",
        duration: 600,
      },
    ],
    appointments: [
      {
        id: "appt1",
        title: "Reunião técnica - Bug página",
        date: "13 Nov, 2024",
        time: "11:00",
        status: "scheduled",
      },
      {
        id: "appt2",
        title: "Teste de correção",
        date: "11 Nov, 2024",
        time: "16:00",
        status: "completed",
      },
    ],
    assignedTo: {
      id: "user1",
      name: "June Jensen",
      avatar: "JJ",
    },
    status: "open",
  },
  {
    id: "6",
    name: "Lucas Ferreira",
    avatar: "LF",
    lastMessage: "Isso começou a acontecer ontem",
    timestamp: "5h",
    unread: false,
    unreadCount: 0,
    channel: "instagram",
    tags: [],
    isPinned: false,
    isImportant: false,
    phone: "+55 11 99876-5432",
    status: "open",
  },
  {
    id: "7",
    name: "Beatriz Alves",
    avatar: "BA",
    lastMessage: "Quando vocês vão lançar a nova funcionalidade?",
    timestamp: "1d",
    unread: false,
    unreadCount: 0,
    channel: "whatsapp",
    tags: ["Suporte"],
    isPinned: false,
    isImportant: false,
    phone: "+55 21 91234-5678",
    callHistory: [
      {
        id: "call1",
        type: "incoming",
        date: "9 Nov, 15:30",
        duration: 520,
      },
      {
        id: "call2",
        type: "outgoing",
        date: "8 Nov, 10:00",
        duration: 280,
      },
    ],
    appointments: [
      {
        id: "appt1",
        title: "Demonstração nova funcionalidade",
        date: "20 Nov, 2024",
        time: "14:30",
        status: "scheduled",
      },
    ],
    assignedTo: {
      id: "user2",
      name: "Anna B",
      avatar: "AB",
    },
    status: "open",
  },
  {
    id: "8",
    name: "Rafael Souza",
    avatar: "RS",
    lastMessage: "Preciso cancelar minha assinatura",
    timestamp: "1d",
    unread: false,
    unreadCount: 0,
    channel: "whatsapp",
    tags: ["Urgente"],
    isPinned: false,
    isImportant: false,
    phone: "+55 11 98765-4321",
    assignedTo: {
      id: "user2",
      name: "Anna B",
      avatar: "AB",
    },
    status: "open",
  },
  {
    id: "9",
    name: "Juliana Lima",
    avatar: "JL",
    lastMessage: "Obrigada pelo atendimento! Funcionou perfeitamente",
    timestamp: "2d",
    unread: false,
    unreadCount: 0,
    channel: "whatsapp",
    tags: [],
    isPinned: false,
    isImportant: false,
    phone: "+55 48 91234-5678",
    callHistory: [
      {
        id: "call1",
        type: "incoming",
        date: "8 Nov, 10:45",
        duration: 420,
      },
      {
        id: "call2",
        type: "outgoing",
        date: "8 Nov, 10:02",
        duration: 180,
      },
    ],
    appointments: [
      {
        id: "appt1",
        title: "Consulta inicial",
        date: "8 Nov, 2024",
        time: "10:00",
        status: "completed",
      },
      {
        id: "appt2",
        title: "Follow-up",
        date: "22 Nov, 2024",
        time: "09:00",
        status: "scheduled",
      },
    ],
    assignedTo: {
      id: "user1",
      name: "June Jensen",
      avatar: "JJ",
    },
    status: "closed",
  },
  {
    id: "10",
    name: "Felipe Martins",
    avatar: "FM",
    lastMessage: "Como faço para integrar com meu sistema?",
    timestamp: "2d",
    unread: false,
    unreadCount: 0,
    channel: "whatsapp",
    tags: ["Suporte"],
    isPinned: false,
    isImportant: false,
    phone: "+55 51 98765-4321",
    assignedTo: {
      id: "user2",
      name: "Anna B",
      avatar: "AB",
    },
    status: "open",
  },
  {
    id: "11",
    name: "Amanda Rocha",
    avatar: "AR",
    lastMessage: "Vocês têm desconto para estudantes?",
    timestamp: "3d",
    unread: false,
    unreadCount: 0,
    channel: "instagram",
    tags: [],
    isPinned: false,
    isImportant: false,
    phone: "+55 85 91234-5678",
    status: "open",
  },
  {
    id: "12",
    name: "Thiago Barbosa",
    avatar: "TB",
    lastMessage: "Meu pagamento foi recusado, o que faço?",
    timestamp: "3d",
    unread: false,
    unreadCount: 0,
    channel: "whatsapp",
    tags: ["Urgente", "Pagamento"],
    isPinned: false,
    isImportant: true,
    phone: "+55 11 97654-3210",
    callHistory: [
      {
        id: "call1",
        type: "missed",
        date: "7 Nov, 15:00",
      },
      {
        id: "call2",
        type: "incoming",
        date: "7 Nov, 15:05",
        duration: 380,
      },
    ],
    appointments: [
      {
        id: "appt1",
        title: "Resolução problema pagamento",
        date: "14 Nov, 2024",
        time: "13:00",
        status: "scheduled",
      },
    ],
    status: "open",
  },
  {
    id: "13",
    name: "Camila Rodrigues",
    avatar: "CR",
    lastMessage: "Gostaria de falar com um supervisor",
    timestamp: "4d",
    unread: false,
    unreadCount: 0,
    channel: "facebook",
    tags: ["Urgente"],
    isPinned: false,
    isImportant: false,
    phone: "+55 21 98765-4321",
    assignedTo: {
      id: "user2",
      name: "Anna B",
      avatar: "AB",
    },
    status: "open",
  },
  {
    id: "14",
    name: "Bruno Dias",
    avatar: "BD",
    lastMessage: "Excelente produto! Recomendo muito",
    timestamp: "5d",
    unread: false,
    unreadCount: 0,
    channel: "whatsapp",
    tags: [],
    isPinned: false,
    isImportant: false,
    phone: "+55 47 99876-5432",
    status: "closed",
  },
  {
    id: "15",
    name: "Fernanda Gomes",
    avatar: "FG",
    lastMessage: "Não consigo fazer login na minha conta",
    timestamp: "5d",
    unread: false,
    unreadCount: 0,
    channel: "whatsapp",
    tags: ["Bug", "Urgente"],
    isPinned: false,
    isImportant: true,
    phone: "+55 11 91234-5678",
    callHistory: [
      {
        id: "call1",
        type: "outgoing",
        date: "5 Nov, 10:30",
        duration: 720,
      },
      {
        id: "call2",
        type: "incoming",
        date: "5 Nov, 10:02",
        duration: 450,
      },
      {
        id: "call3",
        type: "missed",
        date: "4 Nov, 16:20",
      },
    ],
    appointments: [
      {
        id: "appt1",
        title: "Suporte técnico - Login",
        date: "16 Nov, 2024",
        time: "10:00",
        status: "scheduled",
      },
      {
        id: "appt2",
        title: "Verificação conta",
        date: "5 Nov, 2024",
        time: "10:00",
        status: "completed",
      },
      {
        id: "appt3",
        title: "Reunião cancelada",
        date: "4 Nov, 2024",
        time: "16:00",
        status: "cancelled",
      },
    ],
    assignedTo: {
      id: "user1",
      name: "June Jensen",
      avatar: "JJ",
    },
    status: "open",
  },
];

export const mockMessages: Record<string, Message[]> = {
  "1": [
    {
      id: "1",
      sender: "Maria Silva",
      content: "Olá, meu cartão de crédito não está funcionando.",
      timestamp: "10 Nov, 8:00",
      isUser: false,
    },
    {
      id: "2",
      sender: "June Jensen",
      content: "Deixe-me dar uma olhada em como resolver isso para você.",
      timestamp: "10 Nov, 8:03",
      isUser: true,
    },
  ],
  "2": [
    {
      id: "1",
      sender: "João Santos",
      content: "Tenho uma dúvida sobre meu pedido",
      timestamp: "10 Nov, 9:15",
      isUser: false,
    },
    {
      id: "2",
      sender: "June Jensen",
      content: "Claro! Como posso ajudar com seu pedido?",
      timestamp: "10 Nov, 9:16",
      isUser: true,
    },
  ],
  "3": [
    {
      id: "1",
      sender: "Ana Costa",
      content: "O aplicativo está fora do ar?",
      timestamp: "10 Nov, 10:30",
      isUser: false,
    },
    {
      id: "2",
      sender: "June Jensen",
      content: "Não, está funcionando normalmente. Você está tendo algum problema específico?",
      timestamp: "10 Nov, 10:31",
      isUser: true,
    },
    {
      id: "3",
      sender: "Ana Costa",
      content: "Sim, não consigo fazer login",
      timestamp: "10 Nov, 10:32",
      isUser: false,
    },
  ],
  "4": [
    {
      id: "1",
      sender: "Pedro Oliveira",
      content: "Pode me enviar a documentação?",
      timestamp: "10 Nov, 11:00",
      isUser: false,
    },
    {
      id: "2",
      sender: "June Jensen",
      content: "Com certeza! Vou enviar o link da documentação completa.",
      timestamp: "10 Nov, 11:02",
      isUser: true,
    },
  ],
  "5": [
    {
      id: "1",
      sender: "Carla Mendes",
      content: "Criei uma nova página mas não está aparecendo",
      timestamp: "10 Nov, 12:00",
      isUser: false,
    },
    {
      id: "2",
      sender: "June Jensen",
      content: "Vou verificar isso para você. Pode me passar mais detalhes?",
      timestamp: "10 Nov, 12:05",
      isUser: true,
    },
  ],
  "6": [
    {
      id: "1",
      sender: "Lucas Ferreira",
      content: "Isso começou a acontecer ontem",
      timestamp: "9 Nov, 16:00",
      isUser: false,
    },
  ],
  "7": [
    {
      id: "1",
      sender: "Beatriz Alves",
      content: "Quando vocês vão lançar a nova funcionalidade?",
      timestamp: "9 Nov, 14:00",
      isUser: false,
    },
    {
      id: "2",
      sender: "Anna B",
      content: "Estamos trabalhando nisso! A previsão é para o próximo mês.",
      timestamp: "9 Nov, 14:30",
      isUser: true,
    },
  ],
  "8": [
    {
      id: "1",
      sender: "Rafael Souza",
      content: "Preciso cancelar minha assinatura",
      timestamp: "9 Nov, 15:00",
      isUser: false,
    },
    {
      id: "2",
      sender: "Anna B",
      content: "Posso ajudar com isso. Posso perguntar o motivo do cancelamento?",
      timestamp: "9 Nov, 15:05",
      isUser: true,
    },
  ],
  "9": [
    {
      id: "1",
      sender: "Juliana Lima",
      content: "Estava com problema no pagamento",
      timestamp: "8 Nov, 10:00",
      isUser: false,
    },
    {
      id: "2",
      sender: "June Jensen",
      content: "Vou verificar isso para você agora mesmo.",
      timestamp: "8 Nov, 10:02",
      isUser: true,
    },
    {
      id: "3",
      sender: "Juliana Lima",
      content: "Obrigada pelo atendimento! Funcionou perfeitamente",
      timestamp: "8 Nov, 10:45",
      isUser: false,
    },
  ],
  "10": [
    {
      id: "1",
      sender: "Felipe Martins",
      content: "Como faço para integrar com meu sistema?",
      timestamp: "8 Nov, 11:00",
      isUser: false,
    },
    {
      id: "2",
      sender: "Anna B",
      content: "Temos uma documentação completa sobre integrações. Vou te enviar o link.",
      timestamp: "8 Nov, 11:10",
      isUser: true,
    },
  ],
  "11": [
    {
      id: "1",
      sender: "Amanda Rocha",
      content: "Vocês têm desconto para estudantes?",
      timestamp: "7 Nov, 14:00",
      isUser: false,
    },
  ],
  "12": [
    {
      id: "1",
      sender: "Thiago Barbosa",
      content: "Meu pagamento foi recusado, o que faço?",
      timestamp: "7 Nov, 15:00",
      isUser: false,
    },
  ],
  "13": [
    {
      id: "1",
      sender: "Camila Rodrigues",
      content: "Gostaria de falar com um supervisor",
      timestamp: "6 Nov, 10:00",
      isUser: false,
    },
    {
      id: "2",
      sender: "Anna B",
      content: "Vou transferir você para um supervisor. Por favor, aguarde um momento.",
      timestamp: "6 Nov, 10:05",
      isUser: true,
    },
  ],
  "14": [
    {
      id: "1",
      sender: "Bruno Dias",
      content: "Comecei a usar o produto semana passada",
      timestamp: "5 Nov, 9:00",
      isUser: false,
    },
    {
      id: "2",
      sender: "Bruno Dias",
      content: "Excelente produto! Recomendo muito",
      timestamp: "5 Nov, 9:01",
      isUser: false,
    },
  ],
  "15": [
    {
      id: "1",
      sender: "Fernanda Gomes",
      content: "Não consigo fazer login na minha conta",
      timestamp: "5 Nov, 10:00",
      isUser: false,
    },
    {
      id: "2",
      sender: "June Jensen",
      content: "Vou ajudar você com isso. Qual mensagem de erro aparece?",
      timestamp: "5 Nov, 10:02",
      isUser: true,
    },
  ],
};

