import { Conversation, Message } from "@/types/inbox";

export const mockConversations: Conversation[] = [
  {
    id: "1",
    name: "Maria Silva",
    avatar: "MS",
    lastMessage: "Olá, meu cartão de crédito não está funcionando.",
    timestamp: "5min",
    unread: true,
    unreadCount: 3,
    channel: "whatsapp",
    tags: ["Urgente", "Pagamento"],
    isPinned: true,
    isImportant: true,
    assignedTo: {
      id: "user1",
      name: "June Jensen",
      avatar: "JJ",
    },
    status: "open",
  },
  {
    id: "2",
    name: "João Santos",
    avatar: "JS",
    lastMessage: "Tenho uma dúvida sobre meu pedido",
    timestamp: "15min",
    unread: true,
    unreadCount: 1,
    channel: "instagram",
    tags: ["Pedido"],
    isPinned: false,
    isImportant: false,
    assignedTo: {
      id: "user1",
      name: "June Jensen",
      avatar: "JJ",
    },
    status: "open",
  },
  {
    id: "3",
    name: "Ana Costa",
    avatar: "AC",
    lastMessage: "O aplicativo está fora do ar?",
    timestamp: "1h",
    unread: true,
    unreadCount: 2,
    channel: "whatsapp",
    tags: ["Suporte"],
    isPinned: false,
    isImportant: false,
    assignedTo: {
      id: "user1",
      name: "June Jensen",
      avatar: "JJ",
    },
    status: "open",
  },
  {
    id: "4",
    name: "Pedro Oliveira",
    avatar: "PO",
    lastMessage: "Pode me enviar a documentação?",
    timestamp: "2h",
    unread: false,
    unreadCount: 0,
    channel: "instagram",
    tags: [],
    isPinned: false,
    isImportant: false,
    assignedTo: {
      id: "user1",
      name: "June Jensen",
      avatar: "JJ",
    },
    status: "open",
  },
  {
    id: "5",
    name: "Carla Mendes",
    avatar: "CM",
    lastMessage: "Criei uma nova página mas não está aparecendo",
    timestamp: "3h",
    unread: false,
    unreadCount: 0,
    channel: "whatsapp",
    tags: ["Bug"],
    isPinned: false,
    isImportant: true,
    assignedTo: {
      id: "user1",
      name: "June Jensen",
      avatar: "JJ",
    },
    status: "open",
  },
  {
    id: "6",
    name: "Lucas Ferreira",
    avatar: "LF",
    lastMessage: "Isso começou a acontecer ontem",
    timestamp: "5h",
    unread: false,
    unreadCount: 0,
    channel: "instagram",
    tags: [],
    isPinned: false,
    isImportant: false,
    status: "open",
  },
  {
    id: "7",
    name: "Beatriz Alves",
    avatar: "BA",
    lastMessage: "Quando vocês vão lançar a nova funcionalidade?",
    timestamp: "1d",
    unread: false,
    unreadCount: 0,
    channel: "whatsapp",
    tags: ["Suporte"],
    isPinned: false,
    isImportant: false,
    assignedTo: {
      id: "user2",
      name: "Anna B",
      avatar: "AB",
    },
    status: "open",
  },
  {
    id: "8",
    name: "Rafael Souza",
    avatar: "RS",
    lastMessage: "Preciso cancelar minha assinatura",
    timestamp: "1d",
    unread: false,
    unreadCount: 0,
    channel: "instagram",
    tags: ["Urgente"],
    isPinned: false,
    isImportant: false,
    assignedTo: {
      id: "user2",
      name: "Anna B",
      avatar: "AB",
    },
    status: "open",
  },
  {
    id: "9",
    name: "Juliana Lima",
    avatar: "JL",
    lastMessage: "Obrigada pelo atendimento! Funcionou perfeitamente",
    timestamp: "2d",
    unread: false,
    unreadCount: 0,
    channel: "whatsapp",
    tags: [],
    isPinned: false,
    isImportant: false,
    assignedTo: {
      id: "user1",
      name: "June Jensen",
      avatar: "JJ",
    },
    status: "closed",
  },
  {
    id: "10",
    name: "Felipe Martins",
    avatar: "FM",
    lastMessage: "Como faço para integrar com meu sistema?",
    timestamp: "2d",
    unread: false,
    unreadCount: 0,
    channel: "instagram",
    tags: ["Suporte"],
    isPinned: false,
    isImportant: false,
    assignedTo: {
      id: "user2",
      name: "Anna B",
      avatar: "AB",
    },
    status: "open",
  },
  {
    id: "11",
    name: "Amanda Rocha",
    avatar: "AR",
    lastMessage: "Vocês têm desconto para estudantes?",
    timestamp: "3d",
    unread: false,
    unreadCount: 0,
    channel: "whatsapp",
    tags: [],
    isPinned: false,
    isImportant: false,
    status: "open",
  },
  {
    id: "12",
    name: "Thiago Barbosa",
    avatar: "TB",
    lastMessage: "Meu pagamento foi recusado, o que faço?",
    timestamp: "3d",
    unread: false,
    unreadCount: 0,
    channel: "whatsapp",
    tags: ["Urgente", "Pagamento"],
    isPinned: false,
    isImportant: true,
    status: "open",
  },
  {
    id: "13",
    name: "Camila Rodrigues",
    avatar: "CR",
    lastMessage: "Gostaria de falar com um supervisor",
    timestamp: "4d",
    unread: false,
    unreadCount: 0,
    channel: "instagram",
    tags: ["Urgente"],
    isPinned: false,
    isImportant: false,
    assignedTo: {
      id: "user2",
      name: "Anna B",
      avatar: "AB",
    },
    status: "open",
  },
  {
    id: "14",
    name: "Bruno Dias",
    avatar: "BD",
    lastMessage: "Excelente produto! Recomendo muito",
    timestamp: "5d",
    unread: false,
    unreadCount: 0,
    channel: "whatsapp",
    tags: [],
    isPinned: false,
    isImportant: false,
    status: "closed",
  },
  {
    id: "15",
    name: "Fernanda Gomes",
    avatar: "FG",
    lastMessage: "Não consigo fazer login na minha conta",
    timestamp: "5d",
    unread: false,
    unreadCount: 0,
    channel: "instagram",
    tags: ["Bug", "Urgente"],
    isPinned: false,
    isImportant: true,
    assignedTo: {
      id: "user1",
      name: "June Jensen",
      avatar: "JJ",
    },
    status: "open",
  },
];

export const mockMessages: Record<string, Message[]> = {
  "1": [
    {
      id: "1",
      sender: "Maria Silva",
      content: "Olá, meu cartão de crédito não está funcionando.",
      timestamp: "10 Nov, 8:00",
      isUser: true,
    },
    {
      id: "2",
      sender: "June Jensen",
      content: "Deixe-me dar uma olhada em como resolver isso para você.",
      timestamp: "10 Nov, 8:03",
      isUser: false,
    },
  ],
};

