import { Conversation, Message } from "@/types/inbox";

export const mockConversations: Conversation[] = [
  {
    id: "1",
    name: "Hailey Garza",
    avatar: "HG",
    lastMessage: "Hi, my credit card isn't working.",
    timestamp: "2h",
    unread: true,
    unreadCount: 3,
    channel: "whatsapp",
    tags: ["Urgente", "Pagamento"],
    isPinned: true,
    isImportant: true,
    assignedTo: {
      id: "user1",
      name: "June Jensen",
      avatar: "JJ",
    },
    status: "open",
  },
  {
    id: "2",
    name: "Ivan Deen",
    avatar: "ID",
    lastMessage: "Hi, I have a question about my order",
    timestamp: "3h",
    unread: false,
    unreadCount: 0,
    channel: "instagram",
    tags: ["Pedido"],
    isPinned: false,
    isImportant: false,
    assignedTo: {
      id: "user2",
      name: "Anna B",
      avatar: "AB",
    },
    status: "open",
  },
  {
    id: "3",
    name: "Jason Shaw",
    avatar: "JS",
    lastMessage: "Is the app down?",
    timestamp: "5h",
    unread: true,
    unreadCount: 1,
    channel: "whatsapp",
    tags: ["Suporte"],
    isPinned: false,
    isImportant: false,
    status: "open",
  },
  {
    id: "4",
    name: "Robin Benson",
    avatar: "RB",
    lastMessage: "Could you point me to the documentation?",
    timestamp: "1d",
    unread: false,
    unreadCount: 0,
    channel: "instagram",
    tags: [],
    isPinned: false,
    isImportant: false,
    assignedTo: {
      id: "user1",
      name: "June Jensen",
      avatar: "JJ",
    },
    status: "open",
  },
  {
    id: "5",
    name: "Carla Fité",
    avatar: "CF",
    lastMessage: "I created a new page but it's not showing",
    timestamp: "2d",
    unread: false,
    unreadCount: 0,
    channel: "whatsapp",
    tags: ["Bug"],
    isPinned: false,
    isImportant: true,
    status: "closed",
  },
  {
    id: "6",
    name: "Lucy Yoon",
    avatar: "LY",
    lastMessage: "This started happening yesterday",
    timestamp: "3d",
    unread: false,
    unreadCount: 0,
    channel: "instagram",
    tags: [],
    isPinned: false,
    isImportant: false,
    status: "open",
  },
];

export const mockMessages: Record<string, Message[]> = {
  "1": [
    {
      id: "1",
      sender: "Hailey Garza",
      content: "Hi, my credit card isn't working.",
      timestamp: "Nov 9, 8:00 AM",
      isUser: true,
    },
    {
      id: "2",
      sender: "June Jensen",
      content: "Let me take a look on how to solve this issue for you.",
      timestamp: "Nov 9, 8:03 AM",
      isUser: false,
    },
  ],
};

